services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Explizit den Command-Namespace registrieren
  Monosize\DynamicDnsIpUpdater\Command\:
    resource: '../src/Command'
    tags: ['console.command']

  # Den Service-Namespace registrieren
  Monosize\DynamicDnsIpUpdater\Service\:
    resource: '../src/Service'

  # Den DnsUpdaterService explizit konfigurieren
  Monosize\DynamicDnsIpUpdater\Service\DnsUpdaterService:
    arguments:
      $projectDir: '%kernel.project_dir%'